# Generated by Django 5.1.2 on 2024-11-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='adres_degisikligi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documents',
            name='banka_hesabi_acilisi_talebi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documents',
            name='bulut_hizmeti_talebi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documents',
            name='fiziksel_pos_talebi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documents',
            name='hat_talebi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documents',
            name='hgs_talebi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documents',
            name='kep_talebi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documents',
            name='sanal_pos_talebi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documents',
            name='web_sitesi_talebi',
            field=models.BooleanField(default=False),
        ),
    ]
