# Generated by Django 5.1.2 on 2024-11-21 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_documents_adres_degisikligi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documents',
            old_name='Sirket_adi',
            new_name='email',
        ),
    ]
